spring.application.name=demo

openai.api.url=http://localhost:11434/v1/chat/completions

openai.api.key=ollama_local

openai.model=llama3.2at/completions

spring.datasource.url=jdbc:postgresql://localhost:5432/GitHubIssuesCrawlerDB
spring.datasource.username=postgres
spring.datasource.password=new password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect